# Generated by Django 5.0.13 on 2025-08-11 15:18

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Walk-in Freezer', 'Fire Extinguisher #3'",
                        max_length=200,
                    ),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "warranty_document",
                    models.FileField(
                        blank=True, null=True, upload_to=core.models.user_directory_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The legal name of the business.", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Businesses",
            },
        ),
        migrations.CreateModel(
            name="ComplianceTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Annual Fire Safety Inspection'",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "frequency_months",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="How often (in months) should this task be performed?",
                    ),
                ),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("next_due_date", models.DateField()),
                (
                    "completion_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to=core.models.user_directory_path
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["next_due_date"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="core.location",
            ),
        ),
    ]
